version: '3.8'

services:
  stim:
    build:
      context: ./stim
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/stim"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./stim:/app

  main-agent:
    build:
      context: ./main
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/stim"
    ports:
      - "8001:8001"
    volumes:
      - ./main:/app
    depends_on:
      - db

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - stim
      - main-agent
    volumes:
      - ./ui:/app

  db:
    image: postgres
    environment:
      POSTGRES_DB: stim
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
