version: '3.8'

services:
  stim:
    build:
      context: ./stim
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "YOUR_DB_URL"
      DATABASE_KEY: "YOUR_SUPABASE_KEY"      
    ports:
      - "8000:8000"
    volumes:
      - ./stim:/app

  main-agent:
    build:
      context: ./main
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "YOUR_DB_URL"
      DATABASE_KEY: "YOUR_SUPABASE_KEY"
    ports:
      - "8001:8001"
    volumes:
      - ./main:/app

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - stim
      - main-agent
    volumes:
      - ./ui:/app
